version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
nuget:
  account_feed: true
  project_feed: true
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
  # pushing all *.nupkg files in directory
  - path: out\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: ubOtyPLGDRR2As2YTkLUUN8cjmV66GWheJaDWf52o133MIi4Qe3nw0pUDjBkQCA2
  skip_symbols: false
  artifact: /.*\.nupkg/
notifications:
- provider: Email
  to:
  - reinaldo@enkilabs.com.br
  subject: enki.worktime AppVeyor build Fail
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false